### ISSUE TITLE
Travis integration of development version on working-travis

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/development#145]
The integration is successful on macos clang, while on linux gcc and macos gcc there are issues compiling the bindings. On linux clang there are issues when building the precompiled headers for the bindings; this latter issue does not appear on my 18.04 installation though.

**Comment by lgeretti** [comment]
Depends on #126

**Comment by lgeretti** [comment]
The error seems related to the python libraries:

```c++
In file included from /home/travis/build/ariadne-cps/development/build/wrap/cotire/pyariadne-algebra-src_CXX_prefix.hxx:4:
In file included from /home/travis/build/ariadne-cps/development/build/wrap/cotire/pyariadne-algebra-src_CXX_prefix.cxx:5:
In file included from /usr/include/boost/python.hpp:11:
In file included from /usr/include/boost/python/args.hpp:25:
In file included from /usr/include/boost/python/object_core.hpp:14:
In file included from /usr/include/boost/python/call.hpp:15:
In file included from /usr/include/boost/python/converter/arg_to_python.hpp:17:
/usr/include/boost/python/converter/builtin_converters.hpp:172:90: error: no matching member function for call to 'imag'
BOOST_PYTHON_TO_PYTHON_BY_VALUE(std::complex<float>, ::PyComplex_FromDoubles(x.real(), x.imag()), &PyComplex_Type)
```

**Comment by lgeretti** [comment]
Will continue to improve the Travis configuration on the working-travis branch.

**Comment by lgeretti** [comment]
Success. The python part was a bit tricker. In particular for macOS there is an issue compiling with gcc on xcode 9.4, so I had to work using xcode 8.3. Due to that, the python configuration was a bit outdated and more difficult to make work. On the positive side, this is the only configuration that identifies a python2 runtime, so we are able to test that too.
